version: '3'
services:
#  elasticsearch:
#      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
#      volumes:
#        - ./dockercompose/elasticsearch/data:/usr/share/elasticsearch/data
#      ports:
#        - "9202:9200"
#
#      environment:
#        - cluster.name=docker-cluster
##        - bootstrap.memory_lock=true
##        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  es01:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
      container_name: es01
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es02,es03
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./dockercompose/elasticsearch/data01:/usr/share/elasticsearch/data
      ports:
        - 9202:9200

  es02:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
      container_name: es02
      environment:
        - node.name=es02
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es01,es03
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./dockercompose/elasticsearch/data02:/usr/share/elasticsearch/data

  es03:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
      container_name: es03
      environment:
        - node.name=es03
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es01,es02
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./dockercompose/elasticsearch/data03:/usr/share/elasticsearch/data



  kibana:
    depends_on: [ "es01"]
    image: docker.elastic.co/kibana/kibana:7.13.2
#    volumes:
#      - ./dockercompose/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - "5601:5601"
  performance-test-elasticsearch-server:
    depends_on: [ "es01"]
    build: dockercompose/performance-test-java-elasticsearch
    ports:
     - "1405:1405"
    environment:
      SPRING_ELASTICSEARCH_REST_URIS: "http://es01:9200"
    volumes:
     - ./dockercompose/performance-test-java-elasticsearch/app.jar:/home/app.jar